// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-trending-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_trending_posts_default = defineTool({
  name: "list_trending_posts",
  title: "List trending posts",
  description: "List recent public posts from the U\u26A1\uFE0FSportz feed, ordered by most recent.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 10)."),
    sport: z.string().optional().describe("Optional sport filter (e.g. 'basketball').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, sport }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("posts").select("id, caption, sport, video_url, thumbnail_url, likes_count, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (sport) q = q.eq("sport", sport);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-athletes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_athletes_default = defineTool2({
  name: "search_athletes",
  title: "Search athletes",
  description: "Search U\u26A1\uFE0FSportz athlete profiles by name, sport, or position.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Text to match against username, full name, sport, or position."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const like = `%${query}%`;
    const { data, error } = await supabase.from("profiles").select("id, username, full_name, sport, position, bio, avatar_url").or(
      `username.ilike.${like},full_name.ilike.${like},sport.ilike.${like},position.ilike.${like}`
    ).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { athletes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-motivation-quote.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var MOODS = [
  "motivated",
  "relaxed",
  "intense",
  "focused",
  "energetic",
  "calm",
  "pumped",
  "determined"
];
var get_motivation_quote_default = defineTool3({
  name: "get_motivation_quote",
  title: "Get a motivational quote",
  description: "Generate an AI-powered motivational quote for an athlete based on their current mood.",
  inputSchema: {
    mood: z3.enum(MOODS).describe("Athlete's current mood.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ mood }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY not configured" }], isError: true };
    }
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: "You are an inspirational coach. Return one short, powerful motivational quote (1-2 sentences) for an athlete." },
          { role: "user", content: `Generate a motivational quote for someone feeling ${mood}.` }
        ]
      })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `AI gateway error ${res.status}` }], isError: true };
    }
    const data = await res.json();
    const quote = data.choices?.[0]?.message?.content?.trim() ?? "";
    return {
      content: [{ type: "text", text: quote }],
      structuredContent: { quote, mood }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "usportz-mcp",
  title: "U\u26A1\uFE0FSportz MCP",
  version: "0.1.0",
  instructions: "Tools for U\u26A1\uFE0FSportz \u2014 browse trending sports highlights, search athlete profiles, and get AI-generated motivation for athletes.",
  tools: [list_trending_posts_default, search_athletes_default, get_motivation_quote_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
